#ifdef __cplusplus
extern "C"{

/*ESTO PARTE DEL CODIGO HACE QUE PUEDE SER USADO POR PROGRAMAS EN O EN C++*/
#endif

/*DECLARACION DE LA FUNCION, QUE TOMA UN ENTERO Y DEVUELVE UN DOUBLE*/
/*EXTERN INDICA QUE LA FUNCION VA SER DEFINIDA EN OTRO LUGAR*/
extern double reciprocal(int i);

#ifdef __cplusplus

}
#endif